
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - optimize.stormforge.io
  resources:
  - experiments
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - optimize.stormforge.io
  resources:
  - experiments
  - experiments/finalizers
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - optimize.stormforge.io
  resources:
  - trials
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - optimize.stormforge.io
  resources:
  - trials
  - trials/finalizers
  verbs:
  - get
  - list
  - update
  - watch
