name: Matrix workflow
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test Kubernetes Versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Version listings can be found here:
        # https://github.com/kubernetes-sigs/kind/releases
        node:
          - v1.21.1
          - v1.20.7
          - v1.19.11
          - v1.18.19
          - v1.17.17
          - v1.16.15
          - v1.15.12
          - v1.14.10
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: KinD (Kubernetes in Docker) Initialization
        uses: helm/kind-action@v1.1.0
        with:
          version: v0.11.1
          node_image: kindest/node:${{ matrix.node }}
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Build and Deploy"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          intervalSeconds: 30
          timeoutSeconds: 1800
      - name: Fail early if we don't have a successful build
        if: steps.wait-for-build.outputs.conclusion != 'success'
        run: |
          exit 1
      - name: Wait 10s because sleep fixes everything
        run: |
          sleep 10
      - name: Download artifacts from master workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: master.yaml
          name: stormforge_linux_amd64
          path: dist/stormforge_linux_amd64
          commit: ${{ github.event.pull_request.head.sha || github.sha }}
          repo: ${{github.repository}}
      - name: Rename binary because dumbness
        run: |
          tar -zxf dist/stormforge_linux_amd64/stormforge-linux-amd64.tar.gz \
              -C dist/stormforge_linux_amd64
      - name: Run integration tests
        run: |
          hack/integration.sh
      - name: The job has failed
        if: ${{ failure() }}
        run: |
          kubectl get trial,experiment,svc,pod -o wide
          kubectl get pods -o wide -l stormforge.io/experiment=postgres-example
